#!/bin/bash

# Sleeper
#
# Basic commands for a Ruby-on-Rails development environment on Docker

# Prep
if [ "$(docker-machine status)" != 'Running' ]; then
  echo 'Docker not running. Starting...'
  docker-machine start
fi

case "$1" in
setup)
  echo "Building docker images..."
  docker-compose build
  echo "Setting up database..."
  docker-compose run --rm app bundle exec rake db:setup
  ;;
start)
  echo "Starting up... (Press Ctrl + C to stop at any time)"
  docker-compose up
  ;;
open)
  open "http://$(docker-machine ip):$(docker-compose port app 3000 | awk -F ':' '{print $2}')"
  ;;
migrate)
  echo "Migrating database..."
  docker-compose run --rm app bundle exec rake db:migrate
  ;;
seed)
  echo "Adding seed data..."
  docker-compose run --rm app bundle exec rake db:seed
  ;;
console)
  echo "Starting rails console..."
  docker-compose run --rm app bundle exec rails console
  ;;
*)
  echo "Basic commands for a Ruby-on-Rails development environment on Docker"
  echo
  echo "Usage: $0 COMMAND"
  echo
  echo "Commands:"
  echo "  setup     Setup the docker images and database"
  echo "  start     Start the application"
  echo "  open      Open the application in your browser"
  echo "  migrate   Run any pending migrations"
  echo "  seed      Seed the database with example data"
  echo "  console   Start a rails console"
  exit 1
esac
