#!/bin/bash

# Sleeper
#
# Basic commands for a Ruby-on-Rails development environment on Docker

app_run() {
  docker-compose run --rm app "$@"
}

run_rake() {
  app_run rake "$@"
}

run_rails() {
  app_run rails "$@"
}

case "$1" in
setup)
  echo "Building docker images..."
  docker-compose build
  ;;
start)
  echo "Starting up... (Press Ctrl + C to stop at any time)"
  docker-compose up
  ;;
dbsetup)
  echo "Setting up database..."
  docker-compose up -d db
  run_rake db:setup
  ;;
migrate)
  echo "Migrating database..."
  run_rake db:migrate
  ;;
seed)
  echo "Adding seed data..."
  run_rake db:seed
  ;;
console)
  echo "Starting rails console..."
  run_rails console
  ;;
rake)
  run_rake "${@:2}"
  ;;
*)
  echo "Basic commands for a Ruby-on-Rails development environment on Docker"
  echo
  echo "Usage: $0 COMMAND"
  echo
  echo "Commands:"
  echo "  setup     Setup the docker images and database"
  echo "  start     Start the application"
  echo "  open      Open the application in your browser"
  echo "  dbsetup   Setup database"
  echo "  migrate   Run any pending migrations"
  echo "  seed      Seed the database with example data"
  echo "  console   Start a rails console"
  echo "  rake      Run rake tasks"
  exit 1
esac
