#!/bin/bash

# Sleeper
#
# Basic commands for a Ruby-on-Rails development environment on Docker

case "$1" in
setup)
  echo "Building docker images..."
  docker-compose build
  ;;
start)
  echo "Starting up... (Press Ctrl + C to stop at any time)"
  docker-compose up
  ;;
dbsetup)
  echo "Setting up database..."
  docker-compose up -d db
  docker-compose run --rm app bundle exec rake db:setup
  ;;
migrate)
  echo "Migrating database..."
  docker-compose run --rm app bundle exec rake db:migrate
  ;;
seed)
  echo "Adding seed data..."
  docker-compose run --rm app bundle exec rake db:seed
  ;;
console)
  echo "Starting rails console..."
  docker-compose run --rm app bundle exec rails console
  ;;
*)
  echo "Basic commands for a Ruby-on-Rails development environment on Docker"
  echo
  echo "Usage: $0 COMMAND"
  echo
  echo "Commands:"
  echo "  setup     Setup the docker images and database"
  echo "  start     Start the application"
  echo "  open      Open the application in your browser"
  echo "  dbsetup   Setup database"
  echo "  migrate   Run any pending migrations"
  echo "  seed      Seed the database with example data"
  echo "  console   Start a rails console"
  exit 1
esac
